export const pages = document.querySelectorAll('.page'),
             bloks = document.querySelectorAll('.quiz-blok'),
             btnHome = document.querySelector('.category-btn'),
             pageHome = document.querySelector('.quiz-list'),
             boxBlok = document.querySelector('.blok-box'),
             questionBox = document.querySelector('.question-box'),
             artBox = document.querySelector('.art-box'),
             answersBox = document.querySelector('.answers-box'),
             COUNT_OF_RAUNDS = 12;
